# Generated by Django 2.1.2 on 2018-10-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='no title', max_length=100, unique=True),
        ),
    ]
