# Generated by Django 2.1.2 on 2018-11-01 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181101_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='base.Board'),
        ),
    ]
