# Generated by Django 2.2.8 on 2019-12-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20181206_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('pw', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
